In [59]:
# Importing the necessary libraries

import pandas as pd 
import numpy as np 
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [60]:
cars=pd.read_csv("C:\\Users\\HARSH\\OneDrive\\Desktop\\Biz_Machine_Learning\\cars.csv")
cars

,Unnamed: 0,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [61]:
# Cleaning data

In [62]:
cars.isnull().sum()

Unnamed: 0    0
mpg           0
cyl           0
disp          0
hp            0
drat          0
wt            0
qsec          0
vs            0
am            0
gear          0
carb          0
dtype: int64

In [63]:
cars.duplicated().sum()

0

In [64]:
# Detecting outliers using IQR

numeric_features = ['disp', 'hp', 'drat', 'wt', 'qsec', 'mpg']

def detect_outliers_iqr(data, feature):
    Q1 = data[feature].quantile(0.25)
    Q3 = data[feature].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    outliers = data[(data[feature] < lower) | (data[feature] > upper)]
    return outliers

for feature in numeric_features:
    outliers = detect_outliers_iqr(cars, feature)
    print(f"{feature}: {len(outliers)} outlier(s)")

disp: 0 outlier(s)
hp: 1 outlier(s)
drat: 0 outlier(s)
wt: 3 outlier(s)
qsec: 1 outlier(s)
mpg: 1 outlier(s)

In [65]:
# Removing outliers

def remove_outliers_iqr(data, features):
    cleaned_data = data.copy()
    for feature in features:
        Q1 = cleaned_data[feature].quantile(0.25)
        Q3 = cleaned_data[feature].quantile(0.75)
        IQR = Q3 - Q1
        lower = Q1 - 1.5 * IQR
        upper = Q3 + 1.5 * IQR
        cleaned_data = cleaned_data[(cleaned_data[feature] >= lower) & (cleaned_data[feature] <= upper)]
    return cleaned_data

# Define numeric features
numeric_features = ['disp', 'hp', 'drat', 'wt', 'qsec', 'mpg']

# Remove outliers from the DataFrame
cars_cleaned = remove_outliers_iqr(cars, numeric_features)

# Check result
print("Original shape:", cars.shape)
print("Cleaned shape:", cars_cleaned.shape)

Original shape: (32, 12)
Cleaned shape: (27, 12)

In [66]:
# Training and testing the data 

from sklearn.model_selection import train_test_split

X = cars_cleaned.drop(columns=['Unnamed: 0', 'mpg'])  # Features
y = cars_cleaned['mpg']  # Target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=35)

print("Training set size:", X_train.shape)
print("Test set size:", X_test.shape)

Training set size: (20, 10)
Test set size: (7, 10)

In [67]:
# Using the standardScaler for scaling

from sklearn.preprocessing import StandardScaler

features_to_scale = ['disp', 'hp', 'drat', 'wt', 'qsec']

scaler = StandardScaler()
X_scaled = X.copy()
X_scaled[features_to_scale] = scaler.fit_transform(X[features_to_scale])
X_scaled[features_to_scale]

        disp        hp      drat        wt      qsec
0  -0.545591 -0.509393  0.556850 -0.586999 -0.860969
1  -0.545591 -0.509393  0.556850 -0.273414 -0.479214
2  -1.009783 -0.807621  0.464270 -0.955924  0.604698
3   0.329232 -0.509393 -0.961458  0.144700  1.170514
4   1.239763  0.630893 -0.831846  0.421393 -0.479214
5   0.034649 -0.597107 -1.553968  0.445988  1.702244
6   1.239763  1.858894 -0.720750  0.581261 -1.283627
7  -0.664317 -1.351450  0.168015  0.113957  1.552269
9  -0.477747 -0.281336  0.593882  0.421393  0.393369
10 -0.477747 -0.281336  0.593882  0.421393  0.802393
11  0.488129  0.718608 -0.979974  1.196134 -0.220166
12  0.488129  0.718608 -0.979974  0.778020 -0.083825
13  0.488129  0.718608 -0.979974  0.839508  0.188858
14  2.239561  1.157179 -1.239197  2.647236  0.175224
17 -1.271337 -1.281279  0.890137 -1.103493  1.190965
18 -1.298117 -1.526879  2.463993 -1.822896  0.543345
20 -0.901769 -0.737450  0.186531 -0.777610  1.559086
21  0.864839  0.192322 -1.553968  0.519773 -0.581470
22  0.739864  0.192322 -0.831846  0.415245 -0.288336
23  1.150495  1.858894  0.242079  0.913292 -1.576760
24  1.596834  0.630893 -0.961458  0.919441 -0.458763
25 -1.268659 -1.281279  0.890137 -1.429376  0.802393
26 -0.899984 -0.842707  1.538195 -1.177278 -0.697360
27 -1.124938 -0.456764  0.316143 -1.948330 -0.561019
28  1.159422  2.192208  1.149360  0.089362 -2.197112
29 -0.679492  0.630893  0.038403 -0.402537 -1.515407
31 -0.893735 -0.526936  0.945685 -0.390240  0.597881

In [68]:
# Using Linear Regression model

model = LinearRegression()
model.fit(X_train, y_train)

# Predict on test data
y_pred = model.predict(X_test)

# Evaluating the model
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("Model Coefficients:", model.coef_)
print("Intercept:", model.intercept_)
print("Root Mean Squared Error (RMSE):", rmse)
print("R² Score:", r2)

Model Coefficients: [ 3.04894616e-02  2.74150083e-02 -3.49156682e-02  1.23823244e-01
 -6.03440908e+00  1.38857677e+00  4.16393249e-03  6.65015273e-01
  1.77303585e+00  1.56361527e-01]
Intercept: 5.189569300514162
Root Mean Squared Error (RMSE): 1.8941470116928787
R² Score: 0.7032579633492875

In [71]:
# Using k-fold cross validation

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

X = cars_cleaned.drop(columns=["Unnamed: 0", "mpg"])  # Drop car names and target
y = cars_cleaned["mpg"]

# Converting to NumPy arrays
X = X.values
y = y.values

kf = KFold(n_splits=5, shuffle=True, random_state=42)

rmse_scores = []
r2_scores = []

# Performing K-Fold cross validation
for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

    model = LinearRegression()
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    r2 = r2_score(y_test, y_pred)

    rmse_scores.append(rmse)
    r2_scores.append(r2)

print("Average RMSE:", np.mean(rmse_scores))
print("Average R² Score:", np.mean(r2_scores))

Average RMSE: 3.480458479794155
Average R² Score: 0.2624866667289248